---@param theme evergarden.types.theme
---@param config evergarden.types.config
return function(theme, config)
  return {
    DiagnosticFloatingError = { link = 'ErrorFloat' },
    DiagnosticFloatingWarn = { link = 'WarningFloat' },
    DiagnosticFloatingInfo = { link = 'InfoFloat' },
    DiagnosticFloatingHint = { link = 'HintFloat' },
    DiagnosticFloatingOk = { link = 'OkFloat' },
    DiagnosticOk = { theme.diagnostic.ok },
    DiagnosticError = { theme.diagnostic.error },
    DiagnosticWarn = { theme.diagnostic.warn },
    DiagnosticInfo = { theme.diagnostic.info },
    DiagnosticHint = { theme.diagnostic.hint },
    DiagnosticVirtualTextError = { link = 'DiagnosticError' },
    DiagnosticVirtualTextWarn = { link = 'DiagnosticWarn' },
    DiagnosticVirtualTextInfo = { link = 'DiagnosticInfo' },
    DiagnosticVirtualTextHint = { link = 'DiagnosticHint' },
    DiagnosticUnderlineOk = {
      theme.diagnostic.ok,
      theme.none,
      style = { 'underline' },
    },
    DiagnosticUnderlineError = {
      theme.diagnostic.error,
      theme.none,
      style = { 'underline' },
    },
    DiagnosticUnderlineWarn = {
      theme.diagnostic.warn,
      theme.none,
      style = { 'underline' },
    },
    DiagnosticUnderlineInfo = {
      theme.diagnostic.info,
      theme.none,
      style = { 'underline' },
    },
    DiagnosticUnderlineHint = {
      theme.diagnostic.hint,
      theme.none,
      style = { 'underline' },
    },
    DiagnosticSignOk = { theme.diagnostic.ok, theme.sign },
    DiagnosticSignError = { theme.diagnostic.error, theme.sign },
    DiagnosticSignWarn = { theme.diagnostic.warn, theme.sign },
    DiagnosticSignInfo = { theme.diagnostic.info, theme.sign },
    DiagnosticSignHint = { theme.diagnostic.hint, theme.sign },
    LspDiagnosticsFloatingError = { link = 'DiagnosticFloatingError' },
    LspDiagnosticsFloatingWarning = { link = 'DiagnosticFloatingWarn' },
    LspDiagnosticsFloatingInformation = { link = 'DiagnosticFloatingInfo' },
    LspDiagnosticsFloatingHint = { link = 'DiagnosticFloatingHint' },
    LspDiagnosticsDefaultError = { link = 'DiagnosticError' },
    LspDiagnosticsDefaultWarning = { link = 'DiagnosticWarn' },
    LspDiagnosticsDefaultInformation = { link = 'DiagnosticInfo' },
    LspDiagnosticsDefaultHint = { link = 'DiagnosticHint' },
    LspDiagnosticsVirtualTextError = { link = 'DiagnosticVirtualTextError' },
    LspDiagnosticsVirtualTextWarning = { link = 'DiagnosticVirtualTextWarn' },
    LspDiagnosticsVirtualTextInformation = {
      link = 'DiagnosticVirtualTextInfo',
    },
    LspDiagnosticsVirtualTextHint = { link = 'DiagnosticVirtualTextHint' },
    LspDiagnosticsUnderlineError = { link = 'DiagnosticUnderlineError' },
    LspDiagnosticsUnderlineWarning = { link = 'DiagnosticUnderlineWarn' },
    LspDiagnosticsUnderlineInformation = { link = 'DiagnosticUnderlineInfo' },
    LspDiagnosticsUnderlineHint = { link = 'DiagnosticUnderlineHint' },
    LspDiagnosticsSignError = { link = 'DiagnosticSignError' },
    LspDiagnosticsSignWarning = { link = 'DiagnosticSignWarn' },
    LspDiagnosticsSignInformation = { link = 'DiagnosticSignInfo' },
    LspDiagnosticsSignHint = { link = 'DiagnosticSignHint' },

    VirtualTextInfo = { theme.subtext0 },
    LspReferenceText = { bg = theme.surface0 },
    LspReferenceRead = { link = "LspReferenceText" },
    LspReferenceWrite = { link = "LspReferenceText" },
    LspCodeLens = { link = 'VirtualTextInfo' },
    LspCodeLensSeparator = { link = 'MsgSeparator' },
    LspInlayHint = { theme.subtext0 },
    LspSignatureActiveParameter = { link = 'Search' },

    healthError = { link = 'DiagnosticError' },
    healthSuccess = { link = 'DiagnosticOk' },
    healthWarning = { link = 'DiagnosticWarn' },

    DiagnosticDeprecated = {
      theme.diagnostic.warn,
      theme.none,
      style = { 'strikethrough' },
    },
  }
end
